<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ypopup.Core</RootNamespace>
    <AssemblyName>Ypopup.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ypopup.Core.Tests" />
    <InternalsVisibleTo Include="Ypopup.Network.Tests" />
  </ItemGroup>

</Project>
